version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - ls -al
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/simplewar-1.0-SNAPSHOT.war