AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Resources:
  CustomerAppTierAlb:
    Properties:
      Scheme: internal
      Subnets:
        - Fn::ImportValue: !Sub "${NetworksStackNameParm}-PublicGeneralPurposeSubnetAOutput"
        - Fn::ImportValue: !Sub "${NetworksStackNameParm}-PublicGeneralPurposeSubnetBOutput"
        - Fn::ImportValue: !Sub "${NetworksStackNameParm}-PublicGeneralPurposeSubnetCOutput"
      SecurityGroups:
        - Fn::ImportValue: !Sub "${NetworksStackNameParm}-CustomerAppTierAlbSecurityGroupIdOutput"
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
  CustomerAppTierAlbSslListener:
    Properties:
      LoadBalancerArn: !Ref CustomerAppTierAlb
      DefaultActions:
        - TargetGroupArn: !Ref CustomerAppTierAlbTargetGroup
          Type: forward
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: arn:aws:acm:us-west-2:085224677438:certificate/d203faf8-8641-4406-b117-75bd35c100be
    Type: AWS::ElasticLoadBalancingV2::Listener
  CustomerAppTierAlbCname:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: A
      HostedZoneName:
        "Fn::Join":
          - ""
          - - !Ref DomainNameParm
            - "."
      Name:
        "Fn::Join":
          - ""
          - - !Ref HostNameParm
            - "."
            - !Ref DomainNameParm
      AliasTarget:
        HostedZoneId: !GetAtt CustomerAppTierAlb.CanonicalHostedZoneID
        DNSName: !GetAtt CustomerAppTierAlb.DNSName

  CustomerAppTierAlbTargetGroup:
    Properties:
      HealthCheckPath:
        "Fn::Join":
          - ""
          - - "/"
            - !Ref ContextRootParm
            - "/"
            - !Ref HealthCheckPathParm
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTP
      HealthCheckPort: !Ref HealthCheckPortParm
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 3
      VpcId:
        Fn::ImportValue: !Sub "${NetworksStackNameParm}-VpcIdOutput"
      Port: 8080
      Protocol: HTTP
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
  CustomerAppTierAlbListenerRule:
    Properties:
      Actions:
        - TargetGroupArn: !Ref CustomerAppTierAlbTargetGroup
          Type: forward
      Conditions:
        - Field: path-pattern
          Values:
            - !Ref EnvironmentParm
      ListenerArn: !Ref CustomerAppTierAlbSslListener
      Priority: 100
    Type: AWS::ElasticLoadBalancingV2::ListenerRule

  CustomerAppTierAutoscalingGroup:
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MaxBatchSize: 1
        MinInstancesInService: 2
        SuspendProcesses:
          - HealthCheck
          - ReplaceUnhealthy
          - AZRebalance
          - AlarmNotification
          - ScheduledActions
    Properties:
      MaxSize: !Ref CustomerAppAsgMaxSizeParm
      HealthCheckType: ELB
      TargetGroupARNs:
        - !Ref CustomerAppTierAlbTargetGroup
      MinSize: !Ref CustomerAppAsgMinSizeParm
      AvailabilityZones: !Ref CustomerAppAsgAzsParm
      DesiredCapacity: !Ref CustomerAppAsgDesiredCapacityParm
      HealthCheckGracePeriod: !Ref HealthCheckGracePeriodParm
      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub "${NetworksStackNameParm}-PrivateGeneralPurposeSubnetAOutput"
        - Fn::ImportValue: !Sub "${NetworksStackNameParm}-PrivateGeneralPurposeSubnetBOutput"
        - Fn::ImportValue: !Sub "${NetworksStackNameParm}-PrivateGeneralPurposeSubnetCOutput"
      LaunchConfigurationName:
        Fn::ImportValue:
          !Sub "${LaunchConfigurationStackNameParm}-CustomerAppLaunchConfigurationOutput"
    Type: AWS::AutoScaling::AutoScalingGroup
  CustomerAppTierScaleOutPolicy:
    Properties:
      AutoScalingGroupName: !Ref CustomerAppTierAutoscalingGroup
      AdjustmentType: ChangeInCapacity
      PolicyType: SimpleScaling
      ScalingAdjustment: 1
    Type: AWS::AutoScaling::ScalingPolicy
  CustomerAppTierCpuCreditsUsageHighAlarm:
    Properties:
      ComparisonOperator: GreaterThanThreshold
      Threshold: !Ref CustomerAppTierCpuCreditsUsageHighThresholdParm
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref CustomerAppTierAutoscalingGroup
      EvaluationPeriods: 1
      MetricName: CPUCreditUsage
      Namespace: AWS/EC2
      Period: 300
      Statistic: Average
      AlarmActions:
        - !Ref CustomerAppTierScaleOutPolicy
    Type: AWS::CloudWatch::Alarm
  CustomerAppTierScaleInPolicy:
    Properties:
      AutoScalingGroupName: !Ref CustomerAppTierAutoscalingGroup
      AdjustmentType: ChangeInCapacity
      PolicyType: SimpleScaling
      ScalingAdjustment: -1
    Type: AWS::AutoScaling::ScalingPolicy
  CustomerAppTierCpuCreditsUsageLowAlarm:
    Properties:
      ComparisonOperator: LessThanThreshold
      Threshold: !Ref CustomerAppTierCpuCreditsUsageLowThresholdParm
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref CustomerAppTierAutoscalingGroup
      EvaluationPeriods: 36
      MetricName: CPUCreditUsage
      Namespace: AWS/EC2
      Period: 300
      Statistic: Average
      AlarmActions:
        - !Ref CustomerAppTierScaleInPolicy
    Type: AWS::CloudWatch::Alarm
Parameters:
  EnvironmentParm:
    Type: String


  CustomerAppAsgMinSizeParm:
    Type: String
  CustomerAppAsgMaxSizeParm:
    Type: String
  CustomerAppAsgDesiredCapacityParm:
    Type: String
  CustomerAppAsgAzsParm:
    Type: List<AWS::EC2::AvailabilityZone::Name>


  LaunchConfigurationStackNameParm:
    Type: String
  NetworksStackNameParm:
    Type: String

  CustomerAppTierCpuCreditsUsageHighThresholdParm:
    Type: Number
  CustomerAppTierCpuCreditsUsageLowThresholdParm:
    Type: Number
  HealthCheckPathParm:
    Type: String
  DomainNameParm:
    Type: String
  HostNameParm:
    Type: String
  HealthCheckGracePeriodParm:
    Type: Number
  HealthCheckPortParm:
    Type: Number
  ContextRootParm:
    Type: String
